//! # Symbols
//!
//! This module provides lookup for the yahoo api queries

use crate::bitpanda::trade::{Asset, CryptoCurrency, Currency, Fiat};

/// Symbols lookup resolver
pub struct YahooFinanceSymbols;

impl YahooFinanceSymbols {
    /// Get yahoo finance name for an asset
    pub fn lookup(asset: &Asset) -> String {
        match asset {
            Asset::Currency(Currency::Crypto(CryptoCurrency::Aave)) => "AAVE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ach)) => "ACH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ada)) => "ADA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Aergo)) => "AERGO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Agld)) => "AGLD-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Akash)) => "AKASH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Algo)) => "ALGO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Alice)) => "ALICE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ankr)) => "ANKR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ant)) => "ANT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ape)) => "APE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ar)) => "AR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Arpa)) => "ARPA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Astr)) => "ASTR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Atm)) => "ATM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Atom)) => "ATOM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Audio)) => "AUDIO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ava)) => "AVA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Avax)) => "AVAX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Axs)) => "AXS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bake)) => "BAKE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Band)) => "BAND-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bar)) => "BAR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bat)) => "BAT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bch)) => "BCH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Best)) => "BEST-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bico)) => "BICO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Blz)) => "BLZ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bnb)) => "BNB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bnt)) => "BNT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Bnx)) => "BNX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Btc)) => "BTC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Btt)) => "BTT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::C98)) => "C98-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Cake)) => "CAKE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Celo)) => "CELO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Celr)) => "CELR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Chess)) => "CHESS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Chz)) => "CHZ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::City)) => "CITY-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ckb)) => "CKB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Comp)) => "COMP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Coti)) => "COTI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Crv)) => "CRV-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Cspr)) => "CSPR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ctk)) => "CTK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ctsi)) => "CTSI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Cvc)) => "CVC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dash)) => "DASH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dcr)) => "DCR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dgb)) => "DGB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dodo)) => "DODO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Doge)) => "DOGE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dot)) => "DOT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Dusk)) => "DUSK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::DyDx)) => "DYDX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Efi)) => "EFI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Egld)) => "EGLD-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Enj)) => "ENJ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ens)) => "ENS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Eos)) => "EOS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Etc)) => "ETC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Eth)) => "ETH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ethw)) => "ETHW-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Euroc)) => "EUROC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Farm)) => "FARM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Fet)) => "FET-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Fil)) => "FIL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Flow)) => "FLOW-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Flux)) => "FLUX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ftm)) => "FTM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ftt)) => "FTT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Fxs)) => "FXS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Gala)) => "GALA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Glm)) => "GLM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Glmr)) => "GLMR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Gmt)) => "GMT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Gno)) => "GNO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Grt)) => "GRT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Gt)) => "GT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Gtc)) => "GTC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Hbar)) => "HBAR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::High)) => "HIGH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Hnt)) => "HNT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ht)) => "HT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Icp)) => "ICP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Icx)) => "ICX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ilv)) => "ILV-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Imx)) => "IMX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Iost)) => "IOST-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Iotx)) => "IOTX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Iris)) => "IRIS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Joe)) => "JOE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Jst)) => "JST-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Juv)) => "JUV-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Kava)) => "KAVA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Kda)) => "KDA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Klay)) => "KLAY-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Kmd)) => "KMD-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Knc)) => "KNC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ksm)) => "KSM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Lina)) => "LINA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Link)) => "LINK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Looks)) => "LOOKS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Loom)) => "LOOM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Lpt)) => "LPT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Lrc)) => "LRC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Lsk)) => "LSK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ltc)) => "LTC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Luna)) => "LUNA2-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Lunc)) => "LUNA1-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mana)) => "MANA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Matic)) => "MATIC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mbl)) => "MBL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mina)) => "MINA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Miota)) => "MIOTA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mkr)) => "MKR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mln)) => "MLN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mtl)) => "MTL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Mxc)) => "MXC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Near)) => "NEAR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Neo)) => "NEO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Nkn)) => "NKN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ocean)) => "OCEAN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Okb)) => "OKB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Omg)) => "OMG-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::One)) => "ONE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::OneInch)) => "1INCH-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ont)) => "ONT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Op)) => "OP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Orbs)) => "ORBS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Oxt)) => "OXT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Pan)) => "PAN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Perp)) => "PERP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Pla)) => "PLA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Poly)) => "POLY-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Porto)) => "PORTO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Powr)) => "POWR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Psg)) => "PSG-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Pundix)) => "PUNDIX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Qnt)) => "QNT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Qtum)) => "QTUM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Quick)) => "QUICK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rad)) => "RAD-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ray)) => "RAY-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ren)) => "REN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rep)) => "REP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Req)) => "REQ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rndr)) => "RNDR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rsr)) => "RSR-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rune)) => "RUNE-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Rvn)) => "RVN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sand)) => "SAND-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Santos)) => "SANTOS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sc)) => "SC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Scrt)) => "SCRT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sfp)) => "SFP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Shib)) => "SHIB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Skl)) => "SKL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Snt)) => "SNT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Snx)) => "SNX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sol)) => "SOL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Srm)) => "SRM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Stmx)) => "STMX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Storj)) => "STORJ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Stpt)) => "STPT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Strax)) => "STRAX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Stx)) => "STX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sun)) => "SUN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Super)) => "SUPER-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sushi)) => "SUSHI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sxp)) => "SXP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Sys)) => "SYS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Theta)) => "THETA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Tomo)) => "TOMO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Troy)) => "TROY-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Tru)) => "TRU-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Trx)) => "TRX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Tt)) => "TT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Tvk)) => "TVK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Twt)) => "TWT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Uma)) => "UMA-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Uni)) => "UNI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Usdc)) => "USDC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Usdt)) => "USDT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Utk)) => "UTK-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Vet)) => "VET-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Voxel)) => "VOXEL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Vtho)) => "VTHO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Wan)) => "WAN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Waves)) => "WAVES-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Waxp)) => "WAXP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Wemix)) => "WEMIX-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Woo)) => "WOO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xdb)) => "XDB-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xem)) => "XEM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xlm)) => "XLM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xno)) => "XNO-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xrp)) => "XRP-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xrt)) => "XRT-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xtz)) => "XTZ-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xvs)) => "XVS-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Xym)) => "XYM-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Yfi)) => "YFI-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Ygg)) => "YGG-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Zec)) => "ZEC-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Zen)) => "ZEN-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Zil)) => "ZIL-USD".to_string(),
            Asset::Currency(Currency::Crypto(CryptoCurrency::Zrx)) => "ZRX-USD".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Chf)) => "USDCHF=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Czk)) => "USDCZK=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Dkk)) => "USDDKK=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Eur)) => "USDEUR=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Gbp)) => "USDGBP=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Huf)) => "USDHUF=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Pln)) => "USDPLN=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Sek)) => "USDSEK=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Try)) => "USDTRY=x".to_string(),
            Asset::Currency(Currency::Fiat(Fiat::Usd)) => "USDT-USD".to_string(),
            Asset::Metal(metal) => metal.to_string(),
            Asset::Name(name) => name.to_string(),
            Asset::HongKong(id) => format!("{}.HK", id),
        }
    }
}

#[cfg(test)]
mod test {
    use super::*;

    use pretty_assertions::assert_eq;

    #[test]
    fn should_resolve_asset_to_yahoo_symbol() {
        assert_eq!(
            YahooFinanceSymbols::lookup(&Asset::Currency(Currency::Crypto(CryptoCurrency::Btc)))
                .as_str(),
            "BTC-USD"
        );
        assert_eq!(
            YahooFinanceSymbols::lookup(&Asset::Name(String::from("AMZN"))).as_str(),
            "AMZN"
        );
        assert_eq!(
            YahooFinanceSymbols::lookup(&Asset::HongKong(1177)).as_str(),
            "1177.HK"
        );
    }
}
